---
# reboot.yml

- hosts: konrad

  tasks:
    - name: reboot host
      shell: /sbin/shutdown -h now
      become: true

    - name: waiting for server booting up
      local_action: wait_for
      args:
        host: ''
        port: 22
        delay: 30
        timeout: 300
        state: started
      become: false
