---
- hosts: all

  tasks:

  - name: erstellen von /appl
    file:
      path: /appl
      state: directory
    become: true
    become_user: root

  - name: erstellen von /appl/internet
    file:
      path: /appl/internet
      state: directory
    become: true
    become_user: root


  - name: erstellen von /appl/office
    file:
      path: /appl
      state: directory
    become: true
    become_user: root


  - name: erstellen von /appl/Artefakte/data
    file:
      path: /appl/Artefakte/data
      state: directory
    become: true
    become_user: root


  - name: upgrade all packages
    yum: name=* state=latest
    become: true
    become_user: root
    when: ansible_distribution == "CentOS" 

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    become: true 
    become_user: root
    ignore_errors: yes

  - name: Upgrade
    apt:
      name: "*"
      state: latest
    become: true
    become_user: root
    when: ansible_distribution == 'Ubuntu'
  - name: Apps installieren
    apt:
      pkg:
      - thunderbird
      - sshfs
      - curlftpfs
      - curl
      - wget
      - davfs2
      - filezilla
      - snapd
      - git
      - keepass2
      - mutt
      - qtqr
      - python3
      - python-is-python3 
      - python3-pip
      - qrencode
      - pidgin
      - telegram-desktop 
      - proftpd
      - libreoffice-base
      - libreoffice-math
      - knights
      - odbcinst1debian2
      - odbcinst
      - libodbc1
      - sqlite3
      - cheese
      - vokoscreen
      - kdenlive
      - glabels
      - bibletime
      - xskat
      - kpat
      - lskat
      - pokerth
      - kcheckers
      - ksirk
      - kmines
      - marble
      - gimp
      - inetutils-tracerout
      - openboad
      - krusader
      - net-tools
      - pdfgrep
      - zim
      - minidlna
      - gnupg
      - sqlize
    become: true
    become_user: root
    when: ansible_distribution == 'Ubuntu'

  - name: Clean unwanted olderstuff
    apt:
      autoremove: yes
      purge: yes
    become: true
    become_user: root
    when: ansible_distribution == 'Ubuntu'
  - name: snap
    snap: 
      name:
        - ao
        - skype
        - spotify
	- code
    become: true
    become_user: root
    when: ansible_distribution == 'Ubuntu'

  - name: Install Apache @ludwig
    apt:
      pkg: 
      - apache2
    become: true
    become_user: root
    when: "{{ inventory_hostname == 'ludwig' }}"
